<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL57lwfi\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL57lwfi/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerL57lwfi.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerL57lwfi\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerL57lwfi\appProdProjectContainer([
    'container.build_hash' => 'L57lwfi',
    'container.build_id' => 'acdd48f3',
    'container.build_time' => 1683531802,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL57lwfi');
