<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTd6dre3\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTd6dre3/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerTd6dre3.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerTd6dre3\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerTd6dre3\appProdProjectContainer([
    'container.build_hash' => 'Td6dre3',
    'container.build_id' => '5a517ed0',
    'container.build_time' => 1683530383,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTd6dre3');
